[project]
name = "auto-change-gdm-wallpaper"
version = "0.1.0"
description = "Automatically change GDM wallpaper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "watchfiles>=1.0.5",
]
